@echo off
echo Installing Capacitor dependencies...
npm install @capacitor/core @capacitor/app @capacitor/android
npx cap init "Bitfest 2025" "io.ionic.starter" --web-dir "dist"
echo Building the project...
npm run build
echo Adding Android platform...
npx cap add android
echo Syncing Android project...
npx cap sync android
echo Done! You can now open Android Studio with: npx cap open android
